# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 01:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('objective', models.TextField(blank=True, null=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'In process'), (3, 'Finished')])),
                ('clientes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='question.Question')),
            ],
        ),
    ]
