# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(blank=True, through='survey.Survey_Question', to='question.Question'),
        ),
    ]
