# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190718_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_question',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
    ]
