# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 02:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_auto_20190717_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_answer',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('client', 'survey', 'question')]),
        ),
    ]
