# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190718_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_question',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
            preserve_default=False,
        ),
    ]
