# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190717_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='option_response',
            new_name='multiple_choice',
        ),
    ]
