# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190718_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_question',
            name='layout',
            field=models.IntegerField(choices=[(0, 'Vertical'), (1, 'Horizontal')], null=True),
        ),
    ]
