# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190717_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='multiple_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.OptionResponse'),
        ),
    ]
