# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='OptionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('question_type', models.IntegerField(choices=[(0, 'Simple Input'), (1, 'Multiline Input'), (2, 'Unique Choice'), (3, 'Mutiple Choice'), (4, 'Scale')])),
            ],
        ),
        migrations.CreateModel(
            name='Question_OptionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.OptionResponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('objective', models.TextField(blank=True, null=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'In process'), (3, 'Finished')])),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(through='surveyblue_app.Survey_Question', to='surveyblue_app.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(through='surveyblue_app.Question_OptionResponse', to='surveyblue_app.OptionResponse'),
        ),
        migrations.AddField(
            model_name='client_survey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Survey'),
        ),
        migrations.AddField(
            model_name='client',
            name='surveys',
            field=models.ManyToManyField(through='surveyblue_app.Client_Survey', to='surveyblue_app.Survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Client'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.OptionResponse'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Survey'),
        ),
    ]
