# Generated by Django 2.2 on 2019-07-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyblue_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Question_OptionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.OptionResponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Client')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='surveys',
            field=models.ManyToManyField(through='surveyblue_app.Client_Survey', to='surveyblue_app.Survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(through='surveyblue_app.Question_OptionResponse', to='surveyblue_app.OptionResponse'),
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(through='surveyblue_app.Survey_Question', to='surveyblue_app.Question'),
        ),
    ]
