# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyblue_app', '0002_auto_20190716_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Client'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.OptionResponse'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyblue_app.Survey'),
        ),
    ]
