# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Dresciption')),
                ('question_type', models.IntegerField(choices=[(0, 'Simple Input'), (1, 'Multiline Input'), (2, 'Unique Choice'), (3, 'Mutiple Choice'), (4, 'Scale')], verbose_name='Question Type')),
                ('options', models.ManyToManyField(to='question.OptionResponse')),
            ],
        ),
    ]
