# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('question_type', models.IntegerField(choices=[(0, 'Simple Input'), (1, 'Multiline Input'), (2, 'Unique Choice'), (3, 'Mutiple Choice'), (4, 'Scale')])),
            ],
        ),
        migrations.CreateModel(
            name='Question_OptionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.OptionResponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='option', through='question.Question_OptionResponse', to='question.OptionResponse'),
        ),
        migrations.AlterUniqueTogether(
            name='question_optionresponse',
            unique_together=set([('question', 'option_response')]),
        ),
    ]
