# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Simple Input'), (1, 'Multiline Input'), (2, 'Unique Choice'), (3, 'Mutiple Choice'), (4, 'Scale')]),
        ),
    ]
